export const CREATE_COMPANY_REQUEST = 'CREATE_COMPANY_REQUEST';
export const CREATE_COMPANY_FAILURE = 'CREATE_COMPANY_FAILURE';
export const CREATE_COMPANY_SUCCESS = 'CREATE_COMPANY_SUCCESS';
export const CREATE_COMPANY_DUPLICATE = 'CREATE_COMPANY_DUPLICATE';

export const GET_COMPANY = 'GET_COMPANY';
export const GET_COMPANY_REQUEST = 'GET_COMPANY_REQUEST';
export const GET_COMPANY_SUCCESS = 'GET_COMPANY_SUCCESS';
export const GET_COMPANY_FAILURE = 'GET_COMPANY_FAILURE';

export const REMOVE_COMPANY = 'REMOVE_COMPANY';
export const REMOVE_COMPANY_REQUEST = 'REMOVE_COMPANY_REQUEST';
export const REMOVE_COMPANY_SUCCESS = 'REMOVE_COMPANY_SUCCESS';
export const REMOVE_COMPANY_FAILURE = 'REMOVE_COMPANY_FAILURE';

export const CREATE_OFFICE_REQUEST = 'CREATE_OFFICE_REQUEST'
export const CREATE_OFFICE_SUCCESS = 'CREATE_OFFICE_SUCCESS'
export const CREATE_OFFICE_FAILURE = 'CREATE_OFFICE_FAILURE'

export const GET_OFFICE_BY_COMPANY = 'GET_OFFICE_BY_COMPANY'
export const GET_OFFICE_BY_COMPANY_REQUEST = 'GET_OFFICE_BY_COMPANY_REQUEST'
export const GET_OFFICE_BY_COMPANY_SUCCESS = 'GET_OFFICE_BY_COMPANY_REQUEST'
export const GET_OFFICE_BY_COMPANY_FAILURE = 'GET_OFFICE_BY_COMPANY_FAILURE'

export const REMOVE_OFFICE = 'REMOVE_OFFICE';
export const REMOVE_OFFICE_REQUEST = 'REMOVE_OFFICE_REQUEST';
export const REMOVE_OFFICE_SUCCESS = 'REMOVE_OFFICE_SUCCESS';
export const REMOVE_OFFICE_FAILURE = 'REMOVE_OFFICE_FAILURE';
