export const CREATE_COMPANY_REQUEST = 'CREATE_COMPANY_REQUEST';
export const CREATE_COMPANY_FAILURE = 'CREATE_COMPANY_FAILURE';
export const CREATE_COMPANY_SUCCESS = 'CREATE_COMPANY_SUCCESS';
export const CREATE_COMPANY_DUPLICATE = 'CREATE_COMPANY_DUPLICATE';

export const GET_COMPANY = 'GET_COMPANY';
export const GET_COMPANY_REQUEST = 'GET_COMPANY_REQUEST';
export const GET_COMPANY_SUCCESS = 'GET_COMPANY_SUCCESS';
export const GET_COMPANY_FAILURE = 'GET_TOPICS_FAILURE';